### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by ryanmcdermott** [b-rays/aurelia-openID#1]
There are many spots with commented code, this is unnecessary. Version history helps keep you from having to keep that in your codebase! https://github.com/b-rays/aurelia-openID/blob/master/client/src/profile.js#L5

**Comment by b-rays** [comment]
remove commented code - https://github.com/b-rays/aurelia-openID/commit/9b04081e6bd5046a94a40362f2d66f6a7e9b14aa
