### ISSUE TITLE
Classify reusable modules

### ISSUE THREAD

**Issue by ryanmcdermott** [b-rays/aurelia-openID#10]
Break your abstractions into classes, they are easier to use:
https://github.com/b-rays/aurelia-openID/blob/master/server/api/contractor/contractor.controller.js#L15

**Comment by b-rays** [comment]
abstraction of node-email-verification package -https://github.com/b-rays/aurelia-openID/commit/cb63ec7e5c5cca5296048a5fee4d1591ca4d2907
