### ISSUE TITLE
Provider Code

### ISSUE THREAD

**Issue by ryanmcdermott** [b-rays/aurelia-openID#11]
This is hard to reason about, why set the `provider` to `undefined`? Maybe comment this: https://github.com/b-rays/aurelia-openID/blob/master/server/auth/me.controller.js#L51

**Comment by b-rays** [comment]
Provider code update -https://github.com/b-rays/aurelia-openID/commit/ada218d9af34f252b65a3a17dcea2ee6521d36b5
