### ISSUE TITLE
Remove confusing stepwise comments

### ISSUE THREAD

**Issue by ryanmcdermott** [b-rays/aurelia-openID#12]
These are confusing: https://github.com/b-rays/aurelia-openID/blob/master/server/auth/twitter.js#L14

Comment on code that has domain complexity, algorithmic intricacy, or is simply too hard to understand without it. Remember, a comment is an apology. Good naming and abstractions remove the need for comments: http://softwareengineering.stackexchange.com/questions/285787/clean-code-comments-vs-class-documentation

**Comment by b-rays** [comment]
remove stepwise comments - https://github.com/b-rays/aurelia-openID/commit/25297fe34e26d34b071526cd2210cb5d7aa4069b
