### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by ryanmcdermott** [b-rays/aurelia-openID#2]
You should run your code through a formatter, like StandardJS. There's many spots that are hard to read be there's little spacing between keywords/vars/etc and line spacing. E.g: https://github.com/b-rays/aurelia-openID/blob/master/client/src/profile.js#L51

**Comment by ryanmcdermott** [comment]
Another example, this has a totally different tab form. That gets really tough on editors: https://github.com/b-rays/aurelia-openID/blob/master/server/api/labs/labs.contractor.test.js

**Comment by ryanmcdermott** [comment]
https://github.com/b-rays/aurelia-openID/blob/master/client/src/chat.js#L61

**Comment by b-rays** [comment]
Formatting commits; gulpjs-beautifier -https://github.com/b-rays/aurelia-openID/commit/ded094cd881e7c1242754bfcbeb2cc291ff7d763; prettier server - https://github.com/b-rays/aurelia-openID/commit/b3b1dd8a102029b60da527268b113323dfb2fe11
